# Generated by Django 3.0.3 on 2020-02-10 02:17

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notescategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(default='Smith', max_length=50)),
                ('note_type', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='NotesCategories',
        ),
        migrations.AddField(
            model_name='notes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
